### ISSUE TITLE
The React adapter doesn't seem to work outside of Chrome

### ISSUE THREAD

**Issue by erquhart** [layerhq/layer-ui-web#10]
This may apply to more than just the React adapter. Seems related to the use of web components.

Namely, the `properties` property of components is an array in Chrome, and an object in Safari. Calling `filter` on said object breaks the library for Safari.

**Chrome:**
<img width="725" alt="screen shot 2017-02-11 at 8 50 14 pm" src="https://cloud.githubusercontent.com/assets/2112202/22858988/f3377a5e-f09b-11e6-9a1d-c64bf1052d85.png">

**Safari:**
<img width="1040" alt="screen shot 2017-02-11 at 8 49 26 pm" src="https://cloud.githubusercontent.com/assets/2112202/22858993/25fc33d0-f09c-11e6-8108-a1068909155e.png">

**Comment by michaelkantor** [comment]
Needless to say, thats a bit odd.  I have not seen that; `properties` being an array would cause everything to break.  

1. What version are you running?
2. Do you have a sample posted where this can be observed?

Michael

**Comment by erquhart** [comment]
Wondering if it's related to my outdated sdk, like the other ticket. I'll confirm and re-open if the problem persists.
