### ISSUE TITLE
error gets thrown immediately

### ISSUE THREAD

**Issue by kenzanboo** [layerhq/layer-ui-web#13]
Layer ERROR [10:33:53 AM]: This query may need to quote its value

  _fetchData in messages-query is called first with an empty predicate. 
Then its called again with the correct conversation id predicate. the first time causes the it to throw an error. 

Im calling the component like this following the docs:
var conversationPanel = document.createElement('layer-conversation-panel');
          conversationPanel.conversationId = conversation.id;
          document.body.appendChild(conversationPanel);

**Comment by michaelkantor** [comment]
This has been fixed, and is in a PR thats blocked by other projects.  This should not be causing you any issues other than annoying logging which will go away once the blocker lets us merge and ship.
