### ISSUE TITLE
Expose the QueryBuilder's sortBy API to conversation-list-panel

### ISSUE THREAD

**Issue by andela-aabdulwahab** [layerhq/layer-ui-web#18]
I was looking for a way to sort conversations in the `conversation-list-panel`, going through the source code, I realize the `_setupGeneratedQuery` doesn't specify the sortBy for the query builder. This will be a good addition as I currently wish to sort conversation with `lastMessage.sentAt` without having to generate my own query for the component. I want to submit a PR for this, but I can't find your PR Policies and I can see the master branch is a development stage, it currently has failing tests. Can this be added in you next release? And if I'm missing anything, please let me know.

**Comment by michaelkantor** [comment]
I'll see if this is reasonable for the "1.0.0" release that is coming soon.
