### ISSUE TITLE
list-selection _onClick

### ISSUE THREAD

**Issue by mtejedorwolox** [layerhq/layer-ui-web#29]
```js
_onClick(evt) {
  let target = evt.target;
  while (target && target !== this && !target._isListItem) {
    target = target.parentNode;
  }

  if (target.item && target._isListItem) {
    evt.preventDefault();
    evt.stopPropagation();
    this.selectedId = target.item.id;
  }
  this.onClick(evt);
}
```

I understand that maybe the user that subscribes to onClick event wants to know on which target was called the event. But i think that at least we could send to onClick as second parameter the target found in the while statement. I really don't wont to repeat that iteration in my code.

**Comment by michaelkantor** [comment]
`evt.target`: the DOM node that the user clicked upon
`this`: If accessed via the `onClick` Mixin, refers to the Conversation List Item
`this.item`: If accessed via the `onClick` Mixin, refers to the `layer.Conversation` instance represented by this List Item.

**Comment by mtejedorwolox** [comment]
:+1:
