### ISSUE TITLE
The composer is checking for non-existent Layer.Channel

### ISSUE THREAD

**Issue by erquhart** [layerhq/layer-ui-web#9]
Message sending fails because this lib is checking whether the current conversation is an instance of `Layer.Channel`. I'm assuming this is due to this lib being out of sync with the web sdk.

Source here: https://github.com/layerhq/layer-ui-web/blob/master/src/components/subcomponents/layer-composer/layer-composer.js#L258

**Comment by michaelkantor** [comment]
You need to update to the latest WebSDK; Version "3.1.1" has this class:

https://github.com/layerhq/layer-websdk/blob/master/src/models/channel.js
